server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://domain-api:5433/to_do
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    open-in-view: false
