server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/to_do
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    open-in-view: false
