server:
  port: 8081

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

connector:
  rest-api:
    client-url: http://domain-api:8080/api/clients
    task-url: http://domain-api:8080/api/tasks
  token:
    url: http://token-service:8082/api


